# Config file for Air
#
# Create a `.air.toml` file in your project root to configure Air.
# Or, you can specify a custom config file with the `-c` flag.
#
# For more information, see: https://github.com/cosmtrek/air

# The root directory of your project. Defaults to the current directory.
root = "."
# The directory where Air will store its temporary files. Defaults to `tmp`.
tmp_dir = "tmp"

[build]
# The command to build your application.
cmd = "go build -o ./tmp/main ./cmd"
# The path to the binary to run.
bin = "tmp/main"
# The command to run the binary.
full_bin = "./tmp/main"
# File extensions to watch.
include_ext = ["go", "tpl", "tmpl", "html", "env"]
# Directories to exclude from watching.
exclude_dir = ["assets", "tmp", "vendor", "testdata", ".git", "migrations"]
# Files to exclude from watching.
exclude_file = ["*.log", "*.tmp"]
# Directories to watch.
include_dir = ["cmd", "api", "bootstrap", "domain", "infrastructure", "pkg", "repository", "usecase"]
# Log file for build errors.
log = "tmp/air_errors.log"
# Delay in milliseconds before rebuilding.
delay = 1000
# Stop running the application on a build error.
stop_on_error = true
# Send an interrupt signal to the app before killing it.
send_interrupt = false
# Kill the app after this many seconds.
kill_delay = 500

[log]
# Show timestamps in the logs.
time = true

[color]
# Customize colors.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete the tmp directory on exit.
clean_on_exit = true